version: "3"
services:
  db:
    image: postgres:12
    ports:
    - 5432:5432
    volumes:
    - hoteler-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres

volumes:
  hoteler-volume:
    external: true
networks:
  hoteler-network:
    external: true