version: "3"
services:
  hoteler:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8443:8443
    networks:
      - hoteler-network
    env_file: .env
#    links:
#      - db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - hoteler-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hoteler
    networks:
      - hoteler-network

volumes:
  hoteler-volume:
    external: true
networks:
  hoteler-network:
    external: true