version: "3"
services:
  hoteler:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8443:8443
    networks:
      - hoteler-network
    env_file: .env
#    links:
#      - db
    depends_on:
      - db

  db:
    image: postgres:16.2-alpine3.18
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - hoteler-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    networks:
      - hoteler-network
  pgbouncer:
    image: edoburu/pgbouncer:1.22.0-p0
    container_name: 'pgbouncer'
    environment:
      - DATABASE_URL=postgres://postgres:123456@db:5432/postgres
      - POOL_MODE=transaction
      - MAX_DB_CONNECTIONS=100
      - DEFAULT_POOL_SIZE=40
      - AUTH_TYPE=scram-sha-256
    depends_on:
      - db
    ports:
      - 6543:5432
    networks:
      - hoteler-network
    restart: on-failure

  redis:
    image: redis:7.2.4-alpine
    container_name: 'redis'
    ports:
      - 6379:6379
    networks:
      - hoteler-network
    restart: unless-stopped
    volumes:
      - hoteler-redis-volume:/data/redis

volumes:
  hoteler-volume:
    external: true
  hoteler-redis-volume:
    external: true
networks:
  hoteler-network:
    external: true