services:
  hoteler:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hoteler
    restart: always
    ports:
      - 8443:8443
    volumes:
      - ./application-docker.yml:/app/config/application.yml
    networks:
      - hoteler-network
    env_file: .env
    #    links:
    #      - db
    depends_on:
      - db
      - pgbouncer
      - redis

  db:
    image: postgres:17.3-alpine3.20
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - hoteler-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    networks:
      - hoteler-network
  pgbouncer:
    image: edoburu/pgbouncer:v1.24.0-p0
    container_name: "pgbouncer"
    environment:
      - DATABASE_URL=postgres://postgres:123456@db:5432/postgres
      - POOL_MODE=session
      - MAX_DB_CONNECTIONS=100
      - DEFAULT_POOL_SIZE=40
      - AUTH_TYPE=scram-sha-256
    depends_on:
      - db
    ports:
      - 6543:5432
    networks:
      - hoteler-network
    restart: on-failure

  redis:
    image: redis:7.4.1-alpine3.20
    container_name: "redis"
    ports:
      - 6379:6379
    networks:
      - hoteler-network
    restart: unless-stopped
    volumes:
      - hoteler-redis-volume:/data/redis

volumes:
  hoteler-volume:
    external: true
  hoteler-redis-volume:
    external: true
networks:
  hoteler-network:
    external: true
