version: "3"
services:
  hoteler:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8443:8443
    networks:
      - hoteler-network
    env_file: .env
#    links:
#      - db
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine3.18
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - hoteler-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    networks:
      - hoteler-network

  redis:
    image: redis:7.2.1-alpine
    container_name: 'redis'
    ports:
      - 6379:6379
    networks:
      - hoteler-network
    restart: unless-stopped
    volumes:
      - hoteler-redis-volume:/data/redis

volumes:
  hoteler-volume:
    external: true
  hoteler-redis-volume:
    external: true
networks:
  hoteler-network:
    external: true