apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: hoteler-namespace
  labels:
    app: pgbouncer
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: pgbouncer