apiVersion: v1
kind: ConfigMap
metadata:
  name: hoteler-api-config
  namespace: hoteler-namespace
data:
  application.yml: |
    server:
      port: 8443
      compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
    spring:
      data:
        redis:
          host: 127.0.0.1
          port: 6379
          database: 0
          password:
      datasource:
        url: jdbc:postgresql://127.0.0.1:5432/postgres
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver
      flyway:
        enabled: false
        baseline-on-migrate: true
      main:
        allow-bean-definition-overriding: true
    mybatis:
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    secret:
      key: damingerdai
    logger:
      level: info
    springdoc:
      packagesToScan: org.daming.hoteler.api.web
      swagger-ui:
        path: /swagger-ui.html