apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hoteler-api-hpa
  namespace: hoteler-namespace
  labels:
    app: hoteler-api-hpa
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hoteler-api
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50