apiVersion: v1
kind: Service
metadata:
  name: hoteler-api
  namespace: hoteler-namespace
  labels:
    app:  hoteler-api
spec:
  ports:
    - port: 8443
      targetPort: 8443
      nodePort: 30006
  type: NodePort
  selector:
    app: hoteler-api