apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.configMapName }}
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |
    server:
      port: {{ .Values.service.port }}
      compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
    spring:
      threads:
        virtual:
          enabled: true
      data:
        redis:
          host: {{ .Values.redis.host }}
          port: {{ .Values.redis.port }}
          database: {{ .Values.redis.database }}
          password: {{ .Values.redis.password }}
          ssl:
            enabled: {{ .Values.redis.ssl | default false }}
      datasource:
        url: {{ .Values.datasource.url }}
        username: {{ .Values.datasource.username }}
        password: {{ .Values.datasource.password }}
        driver-class-name: org.postgresql.Driver
      flyway:
        enabled: false
        baseline-on-migrate: true
      main:
        allow-bean-definition-overriding: true
      quartz:
        properties:
          org:
            quartz:
              scheduler:
                instanceName: clusteredScheduler
                instanceId: AUTO
              jobStore:
                class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
                driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
                tablePrefix: QRTZ_
                isClustered: true
                clusterCheckinInterval: 10000
                useProperties: false
                misfireThreshold: 60000
                txIsolationLevelSerializable: false # 降低隔离级别可以提升跨网络性能
              threadPool:
                class: org.quartz.simpl.SimpleThreadPool
                threadCount: 10
                threadPriority: 5
                threadsInheritContextClassLoaderOfInitializingThread: true
        job-store-type: jdbc
    mybatis:
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    secret:
      key: damingerdai
    logger:
      level: info
    springdoc:
      packagesToScan: org.daming.hoteler.api.web
      swagger-ui:
        path: /swagger-ui.html
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.app.web.configMapName }}
data:
  backend_url: http://{{ .Values.app.name }}:{{ .Values.service.port }}