apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Values.app.name }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.app.web.name }}
  labels:
    app:  {{ .Values.app.web.name }}
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.service.web.nodePort }}
  type: NodePort
  selector:
    app: {{ .Values.app.web.name }}
