app:
  namespace: hoteler-namespace
  name: hoteler-api
  configMapName: hoteler-api-config
  web:
    name: hoteler-web
    configMapName: hoteler-web-config
    ingress:
      host: hoteler.local

replicaCount: 1

image:
  repository: ghcr.io/damingerdai/hoteler
  tag: "0.0.5"
  pullPolicy: IfNotPresent
  web:
    repository: ghcr.io/damingerdai/hoteler-web
    tag: "0.0.5"
    pullPolicy: IfNotPresent

redis:
  host: redis
  port: 6379
  database: 0
  password: 12345

datasource:
  url: jdbc:postgresql://postgres:5432/postgres
  username: postgres
  password: 123456

service:
  type: NodePort
  port: 8443
  nodePort: 30006
  web:
    nodePort: 30007

hpa:
  replicaCount:
    max: 1
    min: 1
