name: Build and Publish

#on:
#  push:
#    branches: [ master ]
#    paths:
#      - 'src/**'
#      - 'pom.xml'
#      - 'build.gradle'
on:
  push:
    tags:
      - v*

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/damingerdai/hoteler
          tags: |
            type=semver,pattern={{raw}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=ref,event=tag
            type=sha
        env:
          DOCKER_METADATA_SHORT_SHA_LENGTH: 40
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v6
        id: docker_build
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          # push: ${{ github.ref == 'refs/heads/master' }}
          push: true
          # load: true
          platforms: linux/amd64,linux/arm64
          provenance: true
        env:
          DOCKER_METADATA_SHORT_SHA_LENGTH: 40

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Output image tag
        run: echo "image_tag=$(echo ${{ steps.meta.outputs.tags }} | cut -d' ' -f1)" >> $GITHUB_OUTPUT
        id: output_tag

  deploy-to-kubernetes:
    needs: build-and-push-docker-image
    name: Deploy to kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to k3s
        uses: Azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Extract tag name
        id: extract_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Extracted tag name: $TAG_NAME"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
      - name: Deploy to k3s
        run: |-
          kubectl set image deployment/hoteler-api hoteler-api=ghcr.io/damingerdai/hoteler:${{ needs.build-and-push-docker-image.outputs.image_tag }} -n hoteler-namespace
          kubectl rollout status deployment/hoteler-api -n hoteler-namespace --timeout=10m --request-timeout=10m