name: Java CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  REGISTRY_NAME: ghcr.io

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        java-version: [25]
        go-version: ["1.27.0"]
        os: [ubuntu-latest]

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:8.10.0-alpine3.23
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: zulu
          java-version: ${{ matrix.java-version }}
          cache: gradle

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run db migration
        working-directory: migration
        run: |
          go build -o migrate .
          ./migrate up
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: postgres
          POSTGRES_SSLMODE: disable

      - name: Unit Test with Gradle
        run: ./gradlew test -x checkstyleMain -x checkstyleTest
        env:
          CI: true

      - name: Unit Test with Maven
        run: ./mvnw test -Dcheckstyle.skip=true
        env:
          CI: true

      - name: Generate Maven Surefire Report
        if: always()
        run: ./mvnw surefire-report:report-only
        env:
          CI: true

  # Gradle build
  build:
    runs-on: ${{ matrix.os }}
    needs: [test]

    strategy:
      matrix:
        java-version: [25, 27]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v7.0.1

      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: zulu
          java-version: ${{ matrix.java-version }}
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build -x test -x checkstyleMain -x checkstyleTest

  # Maven build
  build-maven:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v7.0.1

      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: zulu
          java-version: "25"
          cache: maven

      - name: Build with Maven
        run: ./mvnw package -Dmaven.test.skip=true -Dcheckstyle.skip=true

  # Docker multi-stage build
  build-docker:
    runs-on: ubuntu-latest
    needs:
      - build
      - build-maven

    steps:
      - uses: actions/checkout@v7.0.1

      - name: Build Docker image with Gradle
        id: build-docker-g
        run: |
          IMAGE="${{ env.REGISTRY_NAME }}/damingerdai/hoteler-g:${{ github.sha }}"

          docker build \
            -t "$IMAGE" \
            -f Dockerfile \
            .

          IMAGE_ID=$(docker image inspect "$IMAGE" --format='{{.Id}}')

          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
          echo "image_id=$IMAGE_ID" >> "$GITHUB_OUTPUT"

      - name: Image ID for Gradle image
        run: |
          echo "Image: ${{ steps.build-docker-g.outputs.image }}"
          echo "Image ID: ${{ steps.build-docker-g.outputs.image_id }}"

      - name: Build Docker image with Maven
        id: build-docker-m
        run: |
          IMAGE="${{ env.REGISTRY_NAME }}/damingerdai/hoteler-m:${{ github.sha }}"

          docker build \
            -t "$IMAGE" \
            -f maven.Dockerfile \
            .

          IMAGE_ID=$(docker image inspect "$IMAGE" --format='{{.Id}}')

          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
          echo "image_id=$IMAGE_ID" >> "$GITHUB_OUTPUT"

      - name: Image ID for Maven image
        run: |
          echo "Image: ${{ steps.build-docker-m.outputs.image }}"
          echo "Image ID: ${{ steps.build-docker-m.outputs.image_id }}"